### PR TITLE
Reimplement CI using Nix

### PR DESCRIPTION
**Pull request by adisbladis**
This adds Nix expressions to build/check tree-sitter-nix and implements a few other required changes:

- Migrate away from the nodejs based `tree-sitter-cli` to `tree-sitter`
The node based one is deprecated and no longer maintained.

- Moves checks from the github yml to flake.nix
Run checks locally with `nix flake check`.

- Regenerate the parser using new `tree-sitter`.

- Adds checks for
   - tree-sitter-nix itself
   - the rust bindings
   - the node bindings
   - editorconfig

Closes https://github.com/nix-community/tree-sitter-nix/issues/37

### CODE REVIEW

**Review by zimbatm — APPROVED** [review]
This looks good to me. It doesn't change functionality, only updates surrounding packages and CI.

**Comment by Kranzes** [comment]
Why not just use our already set-up Hercules-CI?

**Comment by Mic92** [comment]
Does hercules-ci also runs on pull request? I re-call it didn't.

**Comment by Kranzes** [comment]
Nah, that requires using bors or the new github thing...

**Comment by adisbladis** [comment]
> Nah, that requires using bors or the new github thing...

The whole point of this work is to run on third party pull requests and to make it easy for people to fork and hack on. I think a Github Actions based CI aligns better with these goals.

**Comment by cstrahan** [comment]
Awesome, thanks @adisbladis!

**Review by cstrahan — COMMENTED** [review]
:+1:

**Pull request merged**
