### PR TITLE
chore: flake and cargo updates

### PR DESCRIPTION
**Pull request by philiptaron**
Flake updates:

* Updated input 'crane':
    'github:ipetkov/crane/116b32c30b5ff28e49f4fcbeeb1bbe3544593204' (2023-06-21)
  → 'github:ipetkov/crane/b245ee3472cbfd82394047b536e117a32b4c7850' (2024-04-01)
* Removed input 'crane/flake-compat'
* Removed input 'crane/flake-utils'
* Removed input 'crane/flake-utils/systems'
* Removed input 'crane/rust-overlay'
* Removed input 'crane/rust-overlay/flake-utils'
* Removed input 'crane/rust-overlay/nixpkgs'
* Updated input 'flake-utils':
    'github:numtide/flake-utils/dbabf0ca0c0c4bce6ea5eaf65af5cb694d2082c7' (2023-06-25)
  → 'github:numtide/flake-utils/b1d9ab70662946ef0850d488da1c9019f3a9752a' (2024-03-11)
* Updated input 'nix-github-actions':
    'github:nix-community/nix-github-actions/a6a47baf9ca39a942ae5c993a15a7c5c5076274c' (2023-07-08)
  → 'github:nix-community/nix-github-actions/5163432afc817cf8bd1f031418d1869e4c9d5547' (2023-12-29)
* Updated input 'nixpkgs':
    'github:NixOS/nixpkgs/6b3d1b1cf13f407fef5e634b224d575eb7211975' (2023-06-26)
  → 'github:NixOS/nixpkgs/d8fe5e6c92d0d190646fb9f1056741a229980089' (2024-03-29)

Cargo updates:

* updated aho-corasick v1.0.2 -> v1.1.3
* updated cc v1.0.79 -> v1.0.90
* updated memchr v2.5.0 -> v2.7.2
* updated regex v1.8.4 -> v1.10.4
* added regex-automata v0.4.6
* updated regex-syntax v0.7.2 -> v0.8.3

### CODE REVIEW

**Comment by philiptaron** [comment]
@zimbatm @cstrahan

**Comment by adisbladis** [comment]
Why was this merged? CI isn't even passing.

**Comment by philiptaron** [comment]
@adisbladis I'm not near a computer to check on it at the current moment. I do recall doing a `nix-build`. What CI failures are you seeing?

**Comment by adisbladis** [comment]
Look at the big fat zero in the checks and compare that with previous PRs. This completely broke CI.

**Comment by philiptaron** [comment]
> Look at the big fat zero in the checks and compare that with previous PRs. This completely broke CI.

I don't have that in the mobile UI I'm looking at right now. I believe you: could you switch to a mode that's less angry and accusatory and more into a problem solving frame of mind?

**Comment by adisbladis** [comment]
I've spent a not insignificant amount of time getting the CI for this repo up and running, only for all that work to be promptly ignored.
I've already "problem solved" this on master, but I also want to make sure that we don't haphazardly merge stuff again.
 
I'm angry with @zimbatm that this was merged without any actual code review being done.

**Comment by philiptaron** [comment]
Well, I apologize for my part in the matter. This was part of an abortive attempt to integrate tree-sitter-nix into https://github.com/ast-grep/ast-grep, which failed for lack of time.

**Comment by zimbatm** [comment]
I'm sorry. I shouldn't have assumed the change was okay. I think I missed there being a CI in the first place.

What can I do to make it up to you?

**Comment by adisbladis** [comment]
I have expressed what I felt needed expressing. Let's move on :)

**Pull request merged**
