### PR TITLE
Include a generated Wasm File for tree-sitter-web

### PR DESCRIPTION
**Pull request by jeff-hykin**

### CODE REVIEW

**Comment by adisbladis** [comment]
Build outputs shouldn't be vendored in the repository.

**Comment by jeff-hykin** [comment]
Okay, can you put them in a release or somewhere that has a URL endpoint that can be referenced?

**Comment by Atemu** [comment]
If only there was some sort of build tool that can handle building heterogenous software environments...

**Comment by jeff-hykin** [comment]
> If only there was some sort of build tool that can handle building heterogenous software environments...

that's not a fetchable URL endpoint? I don't understand

**Comment by jeff-hykin** [comment]
Come on man :/ I'm just trying to make the software world a better place. I already built it a year ago and put it in my own repo, but I can't setup a webhook to rebuild it every time you make a change. So mine is always out of date. 

The whole point of wasm is that it runs client side, but people can't build the project client side.

So I'd like a not-out-of-date URL that a frontend can pull from.

**Comment by adisbladis** [comment]
If we started cutting releases the wasm grammar could be uploaded to the github releases API.

To do that we'd have to figure out a version number scheme.
I'd suggest something like:
``` nix
${tree-sitter.major}.${tree-sitter.minor}.${patch}
```

`major.minor` would indicate tree-sitter compatibility & patch would be an incrementing counter indicating the release of tree-sitter-nix.

**Comment by jeff-hykin** [comment]
> `major.minor` would indicate tree-sitter compatibility & patch would be an incrementing counter indicating the release of tree-sitter-nix.

That would work perfectly for me!

**Comment by adisbladis** [comment]
Thanks for your contribution @jeff-hykin.

This would be better reported as an issue, or pushed with an updated implementation.
In it's current state it will not be merged, and it serves no one to keep it open.

**Comment by jeff-hykin** [comment]
> This would be better reported as an issue

Understandible, I can do that

**Pull request closed without merging**
